package xyz.syodo.utils.table.blockstate;

import xyz.syodo.utils.ProtocolVersion;
import xyz.syodo.utils.transformer.blocks._1_21_0.*;
import xyz.syodo.utils.transformer.blocks._1_21_20.*;

import static cn.nukkit.block.BlockID.*;
import static xyz.syodo.utils.definition.BlockStateDefinition.of;

public class BlockStateTable_1_21_0 extends BlockStateTable {

    public BlockStateTable_1_21_0() {
        super(ProtocolVersion.MINECRAFT_PE_1_21_0,
                of(SMOOTH_STONE_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(SANDSTONE_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(PETRIFIED_OAK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(COBBLESTONE_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(STONE_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(QUARTZ_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(NETHER_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(SMOOTH_STONE_SLAB, new StoneBlockSlabTransformer()),
                of(SANDSTONE_SLAB, new StoneBlockSlabTransformer()),
                of(PETRIFIED_OAK_SLAB, new StoneBlockSlabTransformer()),
                of(COBBLESTONE_SLAB, new StoneBlockSlabTransformer()),
                of(BRICK_SLAB, new StoneBlockSlabTransformer()),
                of(STONE_BRICK_SLAB, new StoneBlockSlabTransformer()),
                of(QUARTZ_SLAB, new StoneBlockSlabTransformer()),
                of(NETHER_BRICK_SLAB, new StoneBlockSlabTransformer()),
                of(CHISELED_COPPER),
                of(CHISELED_TUFF),
                of(CHISELED_TUFF_BRICKS),
                of(COPPER_BULB),
                of(COPPER_DOOR),
                of(COPPER_GRATE),
                of(COPPER_TRAPDOOR),
                of(CRAFTER),
                of(EXPOSED_CHISELED_COPPER),
                of(EXPOSED_COPPER_BULB),
                of(EXPOSED_COPPER_DOOR),
                of(EXPOSED_COPPER_GRATE),
                of(EXPOSED_COPPER_TRAPDOOR),
                of(HEAVY_CORE),
                of(OXIDIZED_CHISELED_COPPER),
                of(OXIDIZED_COPPER_BULB),
                of(OXIDIZED_COPPER_DOOR),
                of(OXIDIZED_COPPER_GRATE),
                of(OXIDIZED_COPPER_TRAPDOOR),
                of(POLISHED_TUFF),
                of(POLISHED_TUFF_SLAB),
                of(POLISHED_TUFF_DOUBLE_SLAB),
                of(POLISHED_TUFF_STAIRS),
                of(POLISHED_TUFF_WALL),
                of(TRIAL_SPAWNER),
                of(TUFF_BRICK_SLAB),
                of(TUFF_BRICK_DOUBLE_SLAB),
                of(TUFF_BRICK_STAIRS),
                of(TUFF_BRICK_WALL),
                of(TUFF_BRICKS),
                of(TUFF_SLAB),
                of(TUFF_DOUBLE_SLAB),
                of(TUFF_STAIRS),
                of(TUFF_WALL),
                of(VAULT),
                of(WAXED_CHISELED_COPPER),
                of(WAXED_COPPER_BULB),
                of(WAXED_COPPER_DOOR),
                of(WAXED_COPPER_GRATE),
                of(WAXED_COPPER_TRAPDOOR),
                of(WAXED_EXPOSED_CHISELED_COPPER),
                of(WAXED_EXPOSED_COPPER_BULB),
                of(WAXED_EXPOSED_COPPER_DOOR),
                of(WAXED_EXPOSED_COPPER_GRATE),
                of(WAXED_EXPOSED_COPPER_TRAPDOOR),
                of(WAXED_OXIDIZED_CHISELED_COPPER),
                of(WAXED_OXIDIZED_COPPER_BULB),
                of(WAXED_OXIDIZED_COPPER_DOOR),
                of(WAXED_OXIDIZED_COPPER_GRATE),
                of(WAXED_OXIDIZED_COPPER_TRAPDOOR),
                of(WAXED_WEATHERED_CHISELED_COPPER),
                of(WAXED_WEATHERED_COPPER_BULB),
                of(WAXED_WEATHERED_COPPER_DOOR),
                of(WAXED_WEATHERED_COPPER_GRATE),
                of(WAXED_WEATHERED_COPPER_TRAPDOOR),
                of(WEATHERED_CHISELED_COPPER),
                of(WEATHERED_COPPER_BULB),
                of(WEATHERED_COPPER_DOOR),
                of(WEATHERED_COPPER_GRATE),
                of(WEATHERED_COPPER_TRAPDOOR)
                );
    }
}
