package org.powernukkitx.anyversion.utils.table.blockstate;

import org.powernukkitx.anyversion.utils.ProtocolVersion;
import org.powernukkitx.anyversion.utils.transformer.blocks._1_21_110.IronChainTransformer;

import static cn.nukkit.block.BlockID.*;
import static org.powernukkitx.anyversion.utils.definition.BlockStateDefinition.of;

public class BlockStateTable_1_21_110 extends BlockStateTable {

    public BlockStateTable_1_21_110() {
        super(ProtocolVersion.MINECRAFT_PE_1_21_110,
                of(COPPER_BARS),
                of(COPPER_TORCH),
                of(EXPOSED_COPPER_BARS),
                of(OXIDIZED_COPPER_BARS),
                of(WAXED_COPPER_BARS),
                of(WAXED_EXPOSED_COPPER_BARS),
                of(WAXED_OXIDIZED_COPPER_BARS),
                of(WAXED_WEATHERED_COPPER_BARS),
                of(WEATHERED_COPPER_BARS),
                of(COPPER_BULB),
                of(EXPOSED_COPPER_BULB),
                of(OXIDIZED_COPPER_BULB),
                of(WAXED_COPPER_BULB),
                of(WAXED_EXPOSED_COPPER_BULB),
                of(WAXED_OXIDIZED_COPPER_BULB),
                of(WAXED_WEATHERED_COPPER_BULB),
                of(WEATHERED_COPPER_BULB),
                of(COPPER_CHAIN),
                of(EXPOSED_COPPER_CHAIN),
                of(OXIDIZED_COPPER_CHAIN),
                of(WAXED_COPPER_CHAIN),
                of(WAXED_EXPOSED_COPPER_CHAIN),
                of(WAXED_OXIDIZED_COPPER_CHAIN),
                of(WAXED_WEATHERED_COPPER_CHAIN),
                of(WEATHERED_COPPER_CHAIN),
                of(COPPER_CHEST),
                of(EXPOSED_COPPER_CHEST),
                of(OXIDIZED_COPPER_CHEST),
                of(WAXED_COPPER_CHEST),
                of(WAXED_EXPOSED_COPPER_CHEST),
                of(WAXED_OXIDIZED_COPPER_CHEST),
                of(WAXED_WEATHERED_COPPER_CHEST),
                of(WEATHERED_COPPER_CHEST),
                of(COPPER_GOLEM_STATUE),
                of(EXPOSED_COPPER_GOLEM_STATUE),
                of(OXIDIZED_COPPER_GOLEM_STATUE),
                of(WAXED_COPPER_GOLEM_STATUE),
                of(WAXED_EXPOSED_COPPER_GOLEM_STATUE),
                of(WAXED_OXIDIZED_COPPER_GOLEM_STATUE),
                of(WAXED_WEATHERED_COPPER_GOLEM_STATUE),
                of(WEATHERED_COPPER_GOLEM_STATUE),
                of(COPPER_LANTERN),
                of(EXPOSED_COPPER_LANTERN),
                of(OXIDIZED_COPPER_LANTERN),
                of(WAXED_COPPER_LANTERN),
                of(WAXED_EXPOSED_COPPER_LANTERN),
                of(WAXED_OXIDIZED_COPPER_LANTERN),
                of(WAXED_WEATHERED_COPPER_LANTERN),
                of(WEATHERED_COPPER_LANTERN),
                of(LIGHTNING_ROD),
                of(EXPOSED_LIGHTNING_ROD),
                of(OXIDIZED_LIGHTNING_ROD),
                of(WAXED_LIGHTNING_ROD),
                of(WAXED_EXPOSED_LIGHTNING_ROD),
                of(WAXED_OXIDIZED_LIGHTNING_ROD),
                of(WAXED_WEATHERED_LIGHTNING_ROD),
                of(WEATHERED_LIGHTNING_ROD),
                of(ACACIA_SHELF),
                of(BAMBOO_SHELF),
                of(BIRCH_SHELF),
                of(CHERRY_SHELF),
                of(CRIMSON_SHELF),
                of(DARK_OAK_SHELF),
                of(JUNGLE_SHELF),
                of(MANGROVE_SHELF),
                of(OAK_SHELF),
                of(PALE_OAK_SHELF),
                of(SPRUCE_SHELF),
                of(WARPED_SHELF),
                of(IRON_CHAIN, new IronChainTransformer())
        );
    }

}
