package org.powernukkitx.anyversion.utils.table.blockstate;

import org.powernukkitx.anyversion.utils.ProtocolVersion;
import org.powernukkitx.anyversion.utils.transformer.blocks.IdentifierTransformer;
import org.powernukkitx.anyversion.utils.transformer.blocks._1_21_20.*;



import static cn.nukkit.block.BlockID.*;
import static org.powernukkitx.anyversion.utils.definition.BlockStateDefinition.of;

public class BlockStateTable_1_21_20 extends BlockStateTable {

    public BlockStateTable_1_21_20() {
        super(ProtocolVersion.MINECRAFT_PE_1_21_20,
                of(LIGHT_BLOCK_0, new LightBlockTransformer()),
                of(LIGHT_BLOCK_1, new LightBlockTransformer()),
                of(LIGHT_BLOCK_2, new LightBlockTransformer()),
                of(LIGHT_BLOCK_3, new LightBlockTransformer()),
                of(LIGHT_BLOCK_4, new LightBlockTransformer()),
                of(LIGHT_BLOCK_5, new LightBlockTransformer()),
                of(LIGHT_BLOCK_6, new LightBlockTransformer()),
                of(LIGHT_BLOCK_7, new LightBlockTransformer()),
                of(LIGHT_BLOCK_8, new LightBlockTransformer()),
                of(LIGHT_BLOCK_9, new LightBlockTransformer()),
                of(LIGHT_BLOCK_10, new LightBlockTransformer()),
                of(LIGHT_BLOCK_11, new LightBlockTransformer()),
                of(LIGHT_BLOCK_12, new LightBlockTransformer()),
                of(LIGHT_BLOCK_13, new LightBlockTransformer()),
                of(LIGHT_BLOCK_14, new LightBlockTransformer()),
                of(LIGHT_BLOCK_15, new LightBlockTransformer()),
                of(SANDSTONE, new SandstoneTransformer()),
                of(CUT_SANDSTONE, new SandstoneTransformer()),
                of(SMOOTH_SANDSTONE, new SandstoneTransformer()),
                of(CHISELED_SANDSTONE, new SandstoneTransformer()),
                of(RED_SANDSTONE, new RedSandstoneTransformer()),
                of(CUT_RED_SANDSTONE, new RedSandstoneTransformer()),
                of(SMOOTH_RED_SANDSTONE, new RedSandstoneTransformer()),
                of(CHISELED_RED_SANDSTONE, new RedSandstoneTransformer()),
                of(DIRT, new DirtTransformer()),
                of(COARSE_DIRT, new DirtTransformer()),
                of(QUARTZ_BLOCK, new QuartzTransformer()),
                of(CHISELED_QUARTZ_BLOCK, new QuartzTransformer()),
                of(QUARTZ_PILLAR, new QuartzTransformer()),
                of(SMOOTH_QUARTZ, new QuartzTransformer()),
                of(SAND, new SandTransformer()),
                of(RED_SAND, new SandTransformer()),
                of(DANDELION, new IdentifierTransformer("minecraft:yellow_flower")),
                of(ANVIL, new AnvilTransformer()),
                of(DAMAGED_ANVIL, new AnvilTransformer()),
                of(CHIPPED_ANVIL, new AnvilTransformer()),
                of(PRISMARINE_SLAB, new StoneBlockSlab2Transformer()),
                of(DARK_PRISMARINE_SLAB, new StoneBlockSlab2Transformer()),
                of(SMOOTH_SANDSTONE_SLAB, new StoneBlockSlab2Transformer()),
                of(PURPUR_SLAB, new StoneBlockSlab2Transformer()),
                of(RED_NETHER_BRICK_SLAB, new StoneBlockSlab2Transformer()),
                of(PRISMARINE_BRICK_SLAB, new StoneBlockSlab2Transformer()),
                of(MOSSY_COBBLESTONE_SLAB, new StoneBlockSlab2Transformer()),
                of(RED_SANDSTONE_SLAB, new StoneBlockSlab2Transformer()),
                of(SMOOTH_RED_SANDSTONE_SLAB, new StoneBlockSlab3Transformer()),
                of(POLISHED_GRANITE_SLAB, new StoneBlockSlab3Transformer()),
                of(GRANITE_SLAB, new StoneBlockSlab3Transformer()),
                of(POLISHED_DIORITE_SLAB, new StoneBlockSlab3Transformer()),
                of(DIORITE_SLAB, new StoneBlockSlab3Transformer()),
                of(POLISHED_ANDESITE_SLAB, new StoneBlockSlab3Transformer()),
                of(ANDESITE_SLAB, new StoneBlockSlab3Transformer()),
                of(END_STONE_BRICK_SLAB, new StoneBlockSlab3Transformer()),
                of(MOSSY_STONE_BRICK_SLAB, new StoneBlockSlab4Transformer()),
                of(SMOOTH_QUARTZ_SLAB, new StoneBlockSlab4Transformer()),
                of(NORMAL_STONE_SLAB, new StoneBlockSlab4Transformer()),
                of(CUT_SANDSTONE_SLAB, new StoneBlockSlab4Transformer()),
                of(CUT_RED_SANDSTONE_SLAB, new StoneBlockSlab4Transformer()),
                of(PRISMARINE_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(DARK_PRISMARINE_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(SMOOTH_SANDSTONE_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(PURPUR_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(RED_NETHER_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(PRISMARINE_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(MOSSY_COBBLESTONE_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(RED_SANDSTONE_DOUBLE_SLAB, new DoubleStoneBlockSlab2Transformer()),
                of(SMOOTH_RED_SANDSTONE_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(POLISHED_GRANITE_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(GRANITE_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(POLISHED_DIORITE_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(DIORITE_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(POLISHED_ANDESITE_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(ANDESITE_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(END_STONE_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlab3Transformer()),
                of(MOSSY_STONE_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlab4Transformer()),
                of(SMOOTH_QUARTZ_DOUBLE_SLAB, new DoubleStoneBlockSlab4Transformer()),
                of(NORMAL_STONE_DOUBLE_SLAB, new DoubleStoneBlockSlab4Transformer()),
                of(CUT_SANDSTONE_DOUBLE_SLAB, new DoubleStoneBlockSlab4Transformer()),
                of(CUT_RED_SANDSTONE_DOUBLE_SLAB, new DoubleStoneBlockSlab4Transformer()),
                of(SMOOTH_STONE_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(SANDSTONE_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(PETRIFIED_OAK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(COBBLESTONE_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(STONE_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(QUARTZ_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(NETHER_BRICK_DOUBLE_SLAB, new DoubleStoneBlockSlabTransformer()),
                of(PRISMARINE, new PrismarineTransformer()),
                of(PRISMARINE_BRICKS, new PrismarineTransformer()),
                of(DARK_PRISMARINE, new PrismarineTransformer()),
                of(TUBE_CORAL_WALL_FAN, new CoralFanHangTransformer()),
                of(DEAD_TUBE_CORAL_WALL_FAN, new CoralFanHangTransformer()),
                of(BRAIN_CORAL_WALL_FAN, new CoralFanHangTransformer()),
                of(DEAD_BRAIN_CORAL_WALL_FAN, new CoralFanHangTransformer()),
                of(BUBBLE_CORAL_WALL_FAN, new CoralFanHang2Transformer()),
                of(DEAD_BUBBLE_CORAL_WALL_FAN, new CoralFanHang2Transformer()),
                of(FIRE_CORAL_WALL_FAN, new CoralFanHang2Transformer()),
                of(DEAD_FIRE_CORAL_WALL_FAN, new CoralFanHang2Transformer()),
                of(HORN_CORAL_WALL_FAN, new CoralFanHang3Transformer()),
                of(DEAD_HORN_CORAL_WALL_FAN, new CoralFanHang3Transformer()),
                of(INFESTED_COBBLESTONE, new MonsterEggTransformer()),
                of(INFESTED_STONE_BRICKS, new MonsterEggTransformer()),
                of(INFESTED_MOSSY_STONE_BRICKS, new MonsterEggTransformer()),
                of(INFESTED_CRACKED_STONE_BRICKS, new MonsterEggTransformer()),
                of(INFESTED_CHISELED_STONE_BRICKS, new MonsterEggTransformer()),
                of(INFESTED_STONE, new MonsterEggTransformer()),
                of(STONE_BRICKS, new StoneBrickTransformer()),
                of(MOSSY_STONE_BRICKS, new StoneBrickTransformer()),
                of(CRACKED_STONE_BRICKS, new StoneBrickTransformer()),
                of(CHISELED_STONE_BRICKS, new StoneBrickTransformer())
                );
    }
}
